paths:
  runs_root: runs
  run_name: denoiser_proc_overfit

data:
  train_manifest: manifests/music_stems_train.jsonl
  val_manifest:   manifests/music_stems_val.jsonl
  sr: 48000
  crop: 3.0
  mono: true     # ✔ works, but note the task currently mixes channels to mono for STFT.
                 #    If you want *true stereo denoising*, we’d need to keep channels and map masks per channel.
                 #    For overfit sanity, consider mono:true for speed/consistency.
  fixed_index: 0        # always train on item 0
  batch: 1
  workers: 0
  prefetch_factor: 2
  pin_memory: true
  persistent_workers: false

  noise_manifests: []
  use_ext_noise_p: 0.0
  p_clean: 0.0
  out_peak: 0.98

model:
  name: music_unet
  args:
    base: 48
    depth: 5
    out_ch: 1            # ✔ output 1-channel mask; task averages to mono anyway

task:
  name: denoise_stft_music
  args:
    n_fft: 1024
    hop_length: 256
    win_length: 1024
    mask_variant: mag_sigmoid
    mask_floor: 0.30
    mask_limit: 1.80
    clamp_mask_tanh: 0.0
    safe_unity_fallback: true
    return_debug: false  # ✔

losses:
  items:
    - { name: l1_wave, weight: 1.00 }    # ✔ simple overfit sanity; MR-STFT can be added later

optim:
  lr: 1.0e-3
  wd: 0.0
  grad_clip: 0.0
  grad_accum: 1
  warmup_steps: 0
  lr_min_factor: 1.0

train:
  epochs: 5
  save_every: 1
  ema: 0.0

callbacks:
  proc_noise:
    enable: true
    prob: 1.0
    snr_min: 8.0
    snr_max: 8.0
    fixed_seed: 1234
    fixed_per_epoch: true
    require_replace: true   # ✔ fail-fast if a batch is still clean
    train_only: true        # NOTE: validation (audio_debug) will be clean. For noisy debug, set false temporarily.

  audio_debug:
    enable: true
    per_epoch: 3
    scan_batches: 16

  data_audit:
    enable: true
    max_items: 12
    take_from_batches: 6

  save_preds:
    enable: true
    args:
      every_steps: 50
      per_batch: 1
      max_total: 50
      save_triads: true
      out_subdir: logs/pred_dumps

hard_mining: { enable: false }

debug:
  overfit_steps: 2000
  val_every: 1
  val_max_batches: 2
  pbar_every: 8
  print_comp: true

runtime:
  amp: float32           # ✔ for sanity; later you can use bfloat16 for speed if your GPU supports it
  channels_last: true
  cuda_graph: false
  compile: false
  cuda_prefetch: true
  warmup_batches: 0
