paths:
  runs_root: soundrestorer/runs
  run_name: den_progress

data:
  train_manifest: soundrestorer/data/training/train.jsonl
  val_manifest:   soundrestorer/data/training/val.jsonl
  sr: 48000
  crop: 3.0
  mono: true

  batch: 8
  workers: 4            # try 4–6 on Windows
  prefetch_factor: 4
  cache_gb: 0.0
  persistent_workers: true
  pin_memory: true
  no_cache: true

  # dataset-side mixing (if supported by your dataset)
  snr_min: 0.0
  snr_max: 20.0
  use_ext_noise_p: 0.5
  min_clean_rms_db: -40.0
  max_retries: 644
  out_peak: 0.98

  p_clean: 0.10
  add_synth_noise_p: 0.7

  hard_mining:
    enable: true

model:
  # Switch here: complex_unet | complex_unet_lstm | complex_unet_auto
  name: complex_unet_auto
  args:
    base: 48

task:
  name: denoise_stft
  args:
    n_fft: 1024
    hop: 256
    mask_variant: plain
    mask_limit: 1.5     # tightened early; avoids over-boost

losses:
  items:
    - {name: mrstft,      weight: 1.0}
    - {name: l1_wave,     weight: 0.5}
    - {name: sisdr_ratio, weight: 0.30, args: {min_db: 8.0}}
    - {name: mel_l1,      weight: 0.15, args: {sr: 48000, n_mels: 64, n_fft: 1024, hop: 256}}
    - {name: highband_l1, weight: 0.10, args: {sr: 48000, cutoff_khz: 8.0, n_fft: 1024, hop: 256}}
    - {name: phase_cosine,weight: 0.02, args: {n_fft: 1024, hop: 256}}
    - {name: energy_anchor, weight: 0.010}

train:
  epochs: 150
  save_every: 1
  ema: 0.995

optim:
  lr: 4.0e-4
  warmup_steps: 300
  wd: 1.0e-4
  grad_clip: 3.0
  grad_accum: 1

runtime:
  amp: bfloat16
  channels_last: true
  cuda_prefetch: true     # set true if you also add a CUDA prefetcher implementation
  compile: false

hard_mining:
  start_epoch: 3
  ema: 0.9
  top_frac: 0.30
  boost: 4.0
  baseline: 1.0


guard:
  enable: true            # (optional flag; you can ignore in code if you always create it)
  hard_clip: 6.0          # skip batches with loss above this absolute value
  window: 512             # rolling window for robust stats
  mad_k: 6.0              # dynamic outlier threshold (median + k*MAD)
  snr_floor_db: -3.0      # skip if SI-SDR(noisy,clean) < this
  min_rms_db: -70.0       # skip near-silence
  max_peak: 1.2           # skip if input peak is absurdly high
