# configs/denoiser_full.yaml
paths:
  runs_root: runs
  run_name: denoiser_full

data:
  train_manifest: soundrestorer/data/training/train.jsonl
  val_manifest:   soundrestorer/data/training/val.jsonl
  sr: 48000
  crop: 3.0
  mono: true

  batch: 12
  workers: 8
  prefetch_factor: 8
  pin_memory: true
  persistent_workers: true
  cache_gb: 8.0
  no_cache: false

  # dataset-side mixing (if supported by your dataset)
  snr_min: 0.0
  snr_max: 20.0
  use_ext_noise_p: 0.5
  p_clean: 0.05
  out_peak: 0.98
  min_clean_rms_db: -40.0
  max_retries: 24

model:
  name: complex_unet_auto
  args:
    base: 48

task:
  name: denoise_stft
  args:
    n_fft: 1024
    hop: 256
    mask_variant: mag_sigmoid        # bounded, non-zero-grad magnitude mask
    mask_floor: 0.90                # conservative for full training
    mask_limit: 1.08
    clamp_mask_tanh: 0.0             # already bounded by mag_sigmoid
    safe_unity_fallback: true

losses:
  items:
    - { name: mrstft,  weight: 0.70,
        args: { fft_sizes: [1024, 2048], hops: [256, 512], win_lengths: [1024, 2048] } }
    - { name: l1_wave, weight: 0.75 }
    - { name: sisdr_pos, weight: 0.60 , args: { eps: 1.0e-8 } }

optim:
  lr: 3.0e-4
  wd: 1.0e-4
  grad_clip: 3.0
  grad_accum: 1
  warmup_steps: 200
  lr_min_factor: 0.3

train:
  epochs: 60
  save_every: 1
  ema: 0.995

callbacks:
  # open the mask gradually
  curriculum:
    enable: true
    mask_limit: { start: 1.00, end: 1.15, end_epoch: 6 }
    # optionally also relax floor a touch:
    # mask_floor: { start: 0.95, end: 0.90, end_epoch: 6 }

  # train-time blend: dataset noise + procedural noise
  proc_noise:
    enable: true
    prob: 0.8
    snr_min: 0.0
    snr_max: 20.0

  # rescue too-clean train items
  ensure_min_snr:
    enable: true
    min_snr_db: 25.0
    snr_min: 4.0
    snr_max: 20.0
    train_only: true

  # quick listen on validation (filtered)
  audio_debug:
    enable: true
    every: 2
    num_items: 3

  # audit a handful of TRAIN triads, filtered & normalized (first epoch)
  data_audit:
    enable: true
    first_epochs: 1
    max_batches: 3
    max_items: 12
    max_keep_snr_db: 25.0
    max_silence_frac: 0.95
    normalize_peak_dbfs: -1.0
    save_csv: true

hard_mining:
  enable: true
  start_epoch: 3
  ema: 0.9
  top_frac: 0.30
  boost: 4.0
  baseline: 1.0

debug:
  # stable, meaningful validation
  val_every: 1
  val_max_batches: 8
  val_no_clean: true
  sisdr_ignore_if_noisy_gt_db: 25.0
  sisdr_probe_max_batches: 9999

  # console/UI cadence
  pbar_every: 8
  print_comp: true
  print_cuda_mem: false
  step_interval: 0

runtime:
  amp: bfloat16
  channels_last: true
  cuda_graph: false
  compile: true
  compile_backend: inductor
  compile_mode: default
  cuda_prefetch: true
  warmup_batches: 4

guard:
  enable: true
  hard_clip: 0.0
  window: 512
  mad_k: 8.0
  snr_floor_db: -12
  min_rms_db: -70.0
  max_peak: 1.2
